// Scheduling/reservations bounded context (grew out of the bookings BC).
// Owns ResourceType, Resource, SlotClaim, Reservation, ReservationParticipant,
// ReservationPayment, ReservationSeries. Events claim courts via
// ResourceClaimPort; billing is reached via BookingPaymentPort (package C).

export {
  type ActivityFamily,
  type ActivityStats,
  activityFamilyForTypeCode,
  aggregateActivityStats,
  type MemberTier,
  type ResourceType,
  type Resource,
  type Reservation,
  type ReservationParticipant,
  type ReservationPayment,
  type ReservationPendingChange,
  type ReservationStatus,
  type ParticipantRole,
  type ParticipantStatus,
  type ParticipantResponse,
  type MembershipChecker,
  type BookingPaymentPort,
  type PaymentIntentHandle,
  type PaymentStatus,
  type ResourceClaimPort,
  type ClaimedResource,
  type EventClaimConflict,
  type ClubRoster,
  type ClubRosterPort,
  EventClaimConflictError,
  ClubInviteNotAllowedError,
  tierSatisfies,
  SlotUnavailableError,
  OutsideOperatingHoursError,
  InvalidSlotSelectionError,
  MaxReservationsExceededError,
  ReservationTooFarInAdvanceError,
  ReservationInPastError,
  ReservationNotFoundError,
  ResourceTypeNotFoundError,
  ResourceNotFoundError,
  NotReservationOrganizerError,
  TierRequiredError,
  InactiveMembershipError,
  InvalidReservationStatusError,
  ReservationAlreadyStartedError,
  InvalidParticipantTransitionError,
  OrganizerCannotRespondError,
  ParticipantNotFoundError,
  CannotRemoveOrganizerError,
  NotInvitePermittedError,
  InviteeNotFoundError,
  PaymentNotCompletedError,
  HoldExpiredError,
  InsufficientRefundableBalanceError,
  ReservationChangedError,
  SeriesNotFoundError,
  DuplicateSeriesOccurrenceError,
  SeriesInactiveError,
  listSeriesOccurrenceDates,
  weekdayOfDateKey,
} from './domain';
export {
  ReservationService,
  ResourceClaimService,
  SeriesService,
  type CreateSeriesInput,
  type MaterializeResult,
  type AvailabilityDay,
  type QuoteResult,
  type CreateReservationResult,
  type RescheduleQuoteResult,
  type ViewerContext,
} from './application';
export {
  ResourceTypeRepository,
  ResourceRepository,
  ReservationRepository,
  SlotClaimRepository,
  ReservationSeriesRepository,
  PrismaMembershipChecker,
  StubBookingPaymentAdapter,
  type ReservationDetailRecord,
  type SeriesRecord,
  type SeriesAdminRecord,
  type CreateResourceTypeInput,
  type UpdateResourceTypeInput,
  type CreateResourceInput,
  type UpdateResourceInput,
} from './infrastructure';
