// Scheduling/reservations bounded context (grew out of the bookings BC).
// Owns ResourceType, Resource, SlotClaim, Reservation, ReservationParticipant,
// ReservationPayment, ReservationSeries. Events claim courts via
// ResourceClaimPort; billing is reached via BookingPaymentPort (package C).

export {
  type MemberTier,
  type ResourceType,
  type Resource,
  type Reservation,
  type ReservationParticipant,
  type ReservationPayment,
  type ReservationPendingChange,
  type ReservationStatus,
  type ParticipantRole,
  type ParticipantStatus,
  type ParticipantResponse,
  type MembershipChecker,
  type BookingPaymentPort,
  type PaymentIntentHandle,
  type PaymentStatus,
  type ResourceClaimPort,
  type ClaimedResource,
  type EventClaimConflict,
  type ClubRoster,
  type ClubRosterPort,
  EventClaimConflictError,
  ClubInviteNotAllowedError,
  tierSatisfies,
  SlotUnavailableError,
  OutsideOperatingHoursError,
  InvalidSlotSelectionError,
  MaxReservationsExceededError,
  ReservationTooFarInAdvanceError,
  ReservationInPastError,
  ReservationNotFoundError,
  ResourceTypeNotFoundError,
  ResourceNotFoundError,
  NotReservationOrganizerError,
  TierRequiredError,
  InactiveMembershipError,
  InvalidReservationStatusError,
  ReservationAlreadyStartedError,
  InvalidParticipantTransitionError,
  OrganizerCannotRespondError,
  ParticipantNotFoundError,
  CannotRemoveOrganizerError,
  NotInvitePermittedError,
  InviteeNotFoundError,
  PaymentNotCompletedError,
  HoldExpiredError,
  InsufficientRefundableBalanceError,
  ReservationChangedError,
} from './domain';
export {
  ReservationService,
  ResourceClaimService,
  type AvailabilityDay,
  type QuoteResult,
  type CreateReservationResult,
  type RescheduleQuoteResult,
  type ViewerContext,
} from './application';
export {
  ResourceTypeRepository,
  ResourceRepository,
  ReservationRepository,
  SlotClaimRepository,
  PrismaMembershipChecker,
  StubBookingPaymentAdapter,
  type ReservationDetailRecord,
  type CreateResourceTypeInput,
  type UpdateResourceTypeInput,
  type CreateResourceInput,
  type UpdateResourceInput,
} from './infrastructure';
